# Generated by Django 3.0 on 2019-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20191210_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
