# Generated by Django 3.0 on 2019-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20191210_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
